{{- if and (not .Values.loki.existingSecretForConfig) .Values.configAsSecrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "loki.fullname" . }}
  labels:
    {{- include "loki.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{ tpl .Values.loki.config . | nindent 4 | b64enc }}
{{- end -}}
