{{- if and (not .Values.loki.existingSecretForConfig) .Values.configAsSecret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "loki.fullname" . }}
  labels:
    {{- include "loki.labels" . | nindent 4 }}
data:
  config.yaml: {{ tpl .Values.loki.config . | b64enc }}
{{- end -}}
